#ifndef STATE_HPP
#define STATE_HPP

enum State { 
    MAIN_MENU, 
    ADD_INFO, 
    DELETE_INFO, 
    FIND_INFO, 
    SEARCH_INFO,
    ADD_INFO_TEXT,
    ADD_INFO_NUMBER,
    ADD_INFO_MATH,
    ADD_INFO_ADDRESS,
    DELETE_INFO_ID,
    DELETE_INFO_NAME,
    FIND_INFO_ID,
    FIND_INFO_NAME,
};
#endif